swagger: "2.0"
info:
  version: "1.1"
  title: " "
  description: ""

paths:
  /coin:
    post:
      tags:
        - "coin"
      summary: "コインの取得枚数"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              total:
                type: "integer"
              email:
                type: "string"
                format: "string"
             
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                format: "register complete"
  


 
  /user:
    get:
      tags:
        - "user"
      summary: "ユーザーの情報を取得"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          description: "response"
          schema:
            type: "object"
            properties:
              email:
                type: "string"

      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: "object"
              properties:
                email:
                  type: "string"
                total:
                  type: "integer"
                  items:
                    type: "integer"

    post:
      tags:
        - "user"
      summary: "ユーザーの登録"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                format: "string"
              password:
                type: "string"
                format: ""
              name:
                type: "string"
                format: "yyyy-dddd"
      responses:
        200:
          description: "response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                format: "register complete"

    put:
      tags:
        - "user"
      summary: "登録情報の更新"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          description: "response"
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                format: "string"
              password:
                type: "string"
                format: ""
              name:
                type: "string"
                format: "yyyy-dddd"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              message:
                type: "string"

  /login:
    post:
      tags:
        - "login"
      summary: "ログイン"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          description: "response"
          schema:
            type: "object"
            properties:
              email:
                type: "string"
                format: "string"
              password:
                type: "string"
                format: ""

      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              message:
                type: "string"
